### ISSUE TITLE
[BUG] Merging count missing 1 item

### ISSUE THREAD

**Issue by hetile1** [LoneDev6/Issues-ServerBooster#28]
**Describe the bug**
The merging of drop item always miss 1 when grouping them together.

**To Reproduce**
1. make some block drop
2. check the count

**Expected behavior**
The count should match the number of dropped item

**Screenshots**
This is a NEW video recorded with the latest (v1.0.46) version using a regular stone axe
https://youtu.be/Ao4Jn4s5cR4

**Info (please complete the following information):**
 - Server version: Paper version git-Paper-231 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
 - Client version: forge 1.16.3-forge-34.1.19
 - Plugin version: ServerBooster v1.0.46

**Additional context**
Same issue reported here:
https://www.spigotmc.org/threads/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1-paid.401071/page-11#post-3963749
and here:
https://www.spigotmc.org/threads/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1-paid.401071/page-11#post-3967362
and here:
https://www.spigotmc.org/threads/%E2%9C%85must-have%E2%9C%85-serverbooster-%E2%9A%A1optimize-your-server-anti-lag-fps-boost-multilanguage%E2%9A%A1-paid.401071/page-11#post-3967367

Also reported on discord here:
https://discordapp.com/channels/533407895010803753/560530794993680395/762908462547730522

This is the server bootlog:
https://pastebin.com/raw/4EXrWXAu

and the holo config:
```
ubuntu@ns506770:~/minecraft/plugins/ServerBooster$ cat config_holo.yml
lang: en_us
enabled: true
worlds:
- world
- world_nether
- world_the_end
merge:
  force_merge:
    enabled: true
    radius: 12
    max_stack:
      custom: true
      custom_amount: 64
  merge_only_player_drops: false
  hologram:
    enabled: true
    format: '&f{name} &bx{amount}'
    fixes:
      display_amount_3d_model_protocol:
        enabled: true
      invisible_on_login:
        enabled: true
        range: 200
      invisible_on_teleport:
        enabled: true
        range: 200
      invisible_on_respawn:
        enabled: true
        range: 200
    glow:
      enabled: true
      color: AQUA
      only_player_dropped_items: true
      only_current_player: true
  blacklist:
  - BEDROCK
pickup_delay:
  legit_stacks: 2
  unstackable_items_stacks: 2
```
